# Generated by Django 3.1 on 2021-11-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramenapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='author',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='名前'),
        ),
    ]
