# Generated by Django 3.1 on 2021-11-02 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramenapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='mailadress',
            field=models.EmailField(blank=True, help_text='(※入力しておくと、返信があった際に通知します。コメント欄には表示されません。登録の際にメールアドレスを登録している場合必要ありません)', max_length=254, null=True, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='useremail',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ユーザーのメールアドレス'),
        ),
    ]
