# Generated by Django 3.1 on 2021-11-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramenapp', '0002_auto_20211102_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(max_length=500, null=True, verbose_name='ユーザー名'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='author',
            field=models.CharField(max_length=500, null=True, verbose_name='ユーザー名'),
        ),
    ]
