# Generated by Django 3.1.1 on 2020-10-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramenapp', '0004_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
