# Generated by Django 3.1.1 on 2020-10-04 20:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramenapp', '0005_post_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='star',
            field=models.IntegerField(default=3, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='評価'),
        ),
    ]
